# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_version = ">= 202307.0.0"
  config.vm.hostname = "pam-certauth-test"

  config.vm.network "private_network", type: "dhcp"

  config.vm.synced_folder "..", "/srv/source",
    type: "rsync",
    rsync__exclude: ["target/", ".git/", ".idea/"]

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "on"]
  end

  config.vm.provision "shell", path: "provision.sh"
end
