//! Client-to-daemon messages.

use std::time::SystemTime;

use uuid::Uuid;

use crate::session_target::SessionTarget;

/// Metadata captured by the PAM module at session open time.
///
/// Used as the input to [`crate::ClientMessage::SessionOpen`] so that callers
/// can pass it as a single named struct rather than ten positional arguments.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct SessionOpenPayload {
    /// Generated by the PAM module, used to correlate session events.
    pub session_id: Uuid,
    /// The Unix user the session was opened for.
    pub pam_user: String,
    /// The PAM service name (`sshd`, `login`, etc.).
    pub pam_service: String,
    /// Where the session lives (logind id, tty path, display, ...).
    pub target: SessionTarget,
    /// USB serial that authorised the session, when available.
    pub usb_serial: Option<String>,
    /// Hex-encoded host id hash.
    pub host_id_hash: String,
    /// Wall clock time the PAM module decided the session was authenticated.
    #[serde(with = "crate::system_time_serde")]
    pub opened_at: SystemTime,
    /// Common-Name from the validated end-entity certificate.
    pub cert_cn: String,
    /// Hex serial of the validated end-entity certificate.
    pub cert_serial: String,
}

/// Client message.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClientMessage {
    /// Initial hello — must be the first frame on any connection.
    Hello {
        /// Wire-protocol version (matches [`crate::PROTOCOL_VERSION`]).
        protocol_version: u32,
        /// Optional human-readable agent name (`libpam_certauth/0.6.0`).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        agent: Option<String>,
    },
    /// Open a new session.
    SessionOpen {
        /// Session id.
        session_id: Uuid,
        /// PAM user.
        pam_user: String,
        /// PAM service.
        pam_service: String,
        /// Target session.
        target: SessionTarget,
        /// USB serial that authorised the session.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        usb_serial: Option<String>,
        /// Host id hash.
        host_id_hash: String,
        /// Opened at (unix seconds).
        #[serde(with = "crate::system_time_serde")]
        opened_at: SystemTime,
        /// Cert CN.
        cert_cn: String,
        /// Cert serial (hex).
        cert_serial: String,
    },
    /// Close an existing session.
    SessionClose {
        /// Session id.
        session_id: Uuid,
        /// Closed at (unix seconds).
        #[serde(with = "crate::system_time_serde")]
        closed_at: SystemTime,
    },
    /// Liveness check.
    Ping,
}
